### ISSUE TITLE
Display errors around code diff

### ISSUE THREAD

**Issue by mRcfps** [tuture-dev/tuture#150]
There are currently two obvious problems on displaying code diff:

1. incorrect line numbers
2. missing hint for omitted lines of code

Below are screenshots on my newly written tutorial:

Real code:

![image](https://user-images.githubusercontent.com/23410977/65844702-d79d6b00-e369-11e9-9551-12cf3f36e43e.png)

Code diff in editor:

![image](https://user-images.githubusercontent.com/23410977/65844727-f00d8580-e369-11e9-904f-99efaf7eec63.png)

**Note the missing code between Line 10 and Line 18** in the real code.

**Comment by pftom** [comment]
Great! I'll fix it later

**Comment by pftom** [comment]
> 1. incorrect line numbers

The line number also need to sync with it location at real files.

**Comment by pftom** [comment]
I'll close this issue as It as been fixed.
