### ISSUE TITLE
Tuture init topics/categories with Chinese are Lost

### ISSUE THREAD

**Issue by pftom** [tuture-dev/tuture#175]
**Describe the bug**
When I use `tuture init` in a new project, then prompt Tutorial Name, Description, Topics, Categories, The Topics & Categories can add multiply split with `,`, but When I add Chinese words, the final `tuture.yml` result not showing this Chinese word.

**To Reproduce**
1. Project folder
2. Run `tuture init`
3. Response Topics/Categories with Chinese words
4. Final `tuture.yml` not showing this Chinese words

**Expected behavior**
Topics/Categories can add Chinese words as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/26423749/69059343-4b95ee80-0a50-11ea-8bd3-68465c18a986.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Node: v10.16.0
 - Npm: 6.9.0
 - tuture: tuture/2.0.1 darwin-x64 node-v10.16.0

**Comment by mRcfps** [comment]
Closed via #268.
