### ISSUE TITLE
Markdown editor initializes with string "undefined"

### ISSUE THREAD

**Issue by mRcfps** [tuture-dev/tuture#182]
**Describe the bug**
When adding new steps, initialize the markdown editor on empty `explain` blocks and see the string "undefined".

**To Reproduce**
1. Add a new step
2. Click on "Add explanation of this step"
3. The string "undefined" shows up in markdown editor

**Expected behavior**
There should be no "undefined" string.

**Screenshots**
![image](https://user-images.githubusercontent.com/23410977/69707335-8379f180-1134-11ea-95d9-b5fb68f69f70.png)

**Comment by pftom** [comment]
@mRcfps Ok Marc, I'll fix it soon.
