### ISSUE TITLE
error Tuture is not initialized. Run tuture init to initialize.

### ISSUE THREAD

**Issue by hu-qi** [tuture-dev/tuture#194]
**Describe the bug**
您好，我在github上新建了仓库，拉取仓库(空)仓库后进入到目录，执行  **tuture init**，按照要求填写相关信息之后，提示初始化成功，再执行 **tuture  up**, 提示没有初始化。

**To Reproduce**
1. git clone https://github.com/hu-qi/huqi-awesome-tutorial
2. cd huqi-awesome-tutorial/
3. tuture init
4. tuture up

**Expected behavior**
期望能正常打开网页进行文章编写。

**Screenshots**
![image](https://user-images.githubusercontent.com/17986122/76688970-d12b5300-666c-11ea-96b0-7bf50595db9f.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [版本 10.0.17763.1098]
 - Browser: Google Chrome 80.0.3987.122（正式版本）（64 位）
 - Version: null

**Smartphone (please complete the following information):**
 - Device: null
 - OS: null
 - Browser: null
 - Version: null

**Additional context**
初始化之后文件夹目录：    
![image](https://user-images.githubusercontent.com/17986122/76689101-a55c9d00-666d-11ea-9423-b7e871463641.png)

初始化之后配置文件：
![image](https://user-images.githubusercontent.com/17986122/76689116-cd4c0080-666d-11ea-9748-3c1ae4306412.png)
(*奇怪的是github地址中用户名那少了一个 - *)

**Comment by hu-qi** [comment]
初步推测是我网络不稳定导致git出问题了

**Comment by pftom** [comment]
@hu-qi  你好，请问问题解决了嘛？😉

**Comment by hu-qi** [comment]
> @hu-qi 你好，请问问题解决了嘛？😉

解决了，猜到是空仓库的原因，仓库随便提交点东西重新init就正常了。另外git用户名不全的问题应该也是我本地的问题.
![image](https://user-images.githubusercontent.com/17986122/76694851-e32fe480-66b2-11ea-9d08-78d60ffc23ec.png)

![image](https://user-images.githubusercontent.com/17986122/76694870-15d9dd00-66b3-11ea-8071-b933025c6722.png)
