### ISSUE TITLE
error Tuture is not initialized. Run tuture init to initialize.

### ISSUE THREAD

**Issue by hu-qi** [tuture-dev/tuture#195]
**Describe the bug**
您好，我在github上新建了仓库，拉取仓库(空)仓库后进入到目录，执行  **tuture init**，按照要求填写相关信息之后，提示初始化成功，再执行 **tuture  up**, 提示没有初始化。

**To Reproduce**
1. git clone https://github.com/hu-qi/huqi-awesome-tutorial
2. cd huqi-awesome-tutorial/
3. tuture init
4. tuture up

**Expected behavior**
期望能正常打开网页进行文章编写。

**Screenshots**
![image](https://user-images.githubusercontent.com/17986122/76689235-c5409080-666e-11ea-87b1-105c838a3207.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [版本 10.0.17763.1098]
 - Browser: Google Chrome 80.0.3987.122（正式版本）（64 位）
 - Version: null

**Smartphone (please complete the following information):**
 - Device: null
 - OS: null
 - Browser: null
 - Version: null

**Additional context**
初始化之后文件夹目录：    
![image](https://user-images.githubusercontent.com/17986122/76689250-f751f280-666e-11ea-95d8-3ec5081057c6.png)

初始化之后配置文件：
![image](https://user-images.githubusercontent.com/17986122/76689263-13559400-666f-11ea-95f1-62658c8cd0ee.png)

*( 奇怪的是github地址中用户名那少了一个"-")*

**Comment by mRcfps** [comment]
非常感谢你体验 Tuture 写作工具~

1. `Tuture is not initialized` 的问题是因为我们还没有处理好空仓库（还没有任何提交）的边界情况，导致发生了错误的提示。你可以尝试提交一些代码，然后就可以写了哦~
2. `github` 字段发生错误是因为我们在提取仓库的远程地址那边出了一点问题

以上问题我们会尽快解决 😄。由于 Tuture 工具还在紧张的**内测阶段**，问题较多，希望你能谅解。此外，能否加个微信 **little-tuture** 交流沟通一波，我们会努力倾听和解决你的所有问题~

**Comment by hu-qi** [comment]
都是我本地的问题，仓库随便提交点东西重新init就正常了。另外git用户名不全的问题是我git全局设置的用户名不对。
![image](https://user-images.githubusercontent.com/17986122/76694851-e32fe480-66b2-11ea-9d08-78d60ffc23ec.png)

![image](https://user-images.githubusercontent.com/17986122/76694870-15d9dd00-66b3-11ea-8071-b933025c6722.png)

**Comment by pftom** [comment]
@hu-qi  可以有机会加一个微信交流一波哦：little-tuture，我们工具才在早期阶段，希望能获得大家的改进意见，一起💪
