### ISSUE TITLE
Cannot add link with hotkey and click toolbutton

### ISSUE THREAD

**Issue by pftom** [tuture-dev/tuture#215]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Can insert link with hotkey or click link toolbutton

**Screenshots**

![2020-03-27 11-13-11 2020-03-27 11_14_42](https://user-images.githubusercontent.com/26423749/77717767-3ba0a380-701c-11ea-9913-ef49d139edfb.gif)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mRcfps** [comment]
Yes, I'll handle it. This is related to updated editure APIs.
