### ISSUE TITLE
Tsify issue collection

### ISSUE THREAD

**Issue by pftom** [tuture-dev/tuture#219]

**Comment by pftom** [comment]
Link shortcut issue 
![2020-03-31 17-56-23 2020-03-31 17_57_01](https://user-images.githubusercontent.com/26423749/78013485-222f8c80-7379-11ea-9ef3-98c32d449af6.gif)

**Comment by pftom** [comment]
Link toolbutton issue
![2020-03-31 17-58-36 2020-03-31 17_59_03](https://user-images.githubusercontent.com/26423749/78013736-82263300-7379-11ea-9a65-e999e99fc366.gif)

**Comment by pftom** [comment]
1.Note toolbutton click will lose focus

![2020-03-31 18-02-45 2020-03-31 18_04_17](https://user-images.githubusercontent.com/26423749/78014142-15f7ff00-737a-11ea-872c-60106880b357.gif)

2. numbered/unordered list toolbutton click will throw error

![2020-03-31 18-07-03 2020-03-31 18_07_32](https://user-images.githubusercontent.com/26423749/78014484-93bc0a80-737a-11ea-9a70-c44221b3f11c.gif)

**Comment by pftom** [comment]
1. File switch cannot success

![2020-03-31 18-11-14 2020-03-31 18_12_18](https://user-images.githubusercontent.com/26423749/78014945-37a5b600-737b-11ea-9f48-77c0eb917654.gif)

2. Create new page error

 
![2020-03-31 18-13-46 2020-03-31 18_14_42](https://user-images.githubusercontent.com/26423749/78015142-8d7a5e00-737b-11ea-8b4f-a4da154a2114.gif)

**Comment by mRcfps** [comment]
Closed via #221.
