### ISSUE TITLE
Outdated steps cannot release

### ISSUE THREAD

**Issue by pftom** [tuture-dev/tuture#220]
**Describe the bug**

**To Reproduce**
Go to  "Step arrange page", release outdated steps and save, the outdated step will re-add to the right step list"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mRcfps** [comment]
@pftom Please describe how to replicate the issue in detail.

**Comment by pftom** [comment]
@mRcfps No problem

**Comment by pftom** [comment]
![2020-04-02 12-42-39 2020-04-02 12_43_23](https://user-images.githubusercontent.com/26423749/78211444-94ba7c80-74df-11ea-83e2-1a0c015517a2.gif)
@mRcfps

**Comment by mRcfps** [comment]
This is closed via #221.
