### ISSUE TITLE
Steps arrange issue

### ISSUE THREAD

**Issue by pftom** [tuture-dev/tuture#236]
**Describe the bug**
Release steps and save will result error

**To Reproduce**
1. Go to 'step arrange'
2. Click on 'release steps'
3. Click 'save' 
4. See 'step recover'

**Expected behavior**

**Screenshots**
![2020-04-09 12-22-28 2020-04-09 12_23_51](https://user-images.githubusercontent.com/26423749/78857807-ff7a3380-7a5c-11ea-9d4f-9e3a823b2e97.gif)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mRcfps** [comment]
Closed via #237.
