### ISSUE TITLE
Click diffblock result white screen

### ISSUE THREAD

**Issue by pftom** [tuture-dev/tuture#248]
**Describe the bug**
Click selectbox with diffblock will result white screen

**To Reproduce**

**Expected behavior**

**Screenshots**
![2020-04-18 11-49-38 2020-04-18 11_50_40](https://user-images.githubusercontent.com/26423749/79627449-e2cfb100-816a-11ea-8996-d136850b92f6.gif)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mRcfps** [comment]
This issue has been resolved.
