### ISSUE TITLE
初始化项目时没有添加 version 字段，导致 hiddenLines 兼容性修改出错

### ISSUE THREAD

**Issue by pftom** [tuture-dev/tuture#257]
**Describe the bug**
`tuture init` exist project, and then `tuture up` start the project will result flatMap error

**To Reproduce**
1. `git clone https://github.com/Bluestar123/ublog.git`
2. `cd unblog && tuture init -y`
3. `tuture up`

**Expected behavior**
`tuture up` can successfully start the tutorial

**Screenshots**
![image](https://user-images.githubusercontent.com/26423749/80276381-f1920700-871a-11ea-8d84-2c53a5ad6540.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mRcfps** [comment]
This is due to missing `version` field.
