### ISSUE TITLE
代码不同步更新

### ISSUE THREAD

**Issue by AutumnFish** [tuture-dev/tuture#292]
**简要描述 Bug**
git add commit 之后 写作界面代码部分不显示，需要重新 tuture up

**Tuture 版本信息**
@tuture/cli/0.0.4 darwin-x64 node-v13.13.0

**详细的报错调用栈信息**
终端或者浏览器控制台的任何报错信息，请直接复制在这里。

**复现步骤**
复现 Bug 的完整步骤：

1. tuture up 开启 图雀
2. 编辑代码并 git add commit 记录此次操作
3. 刷新浏览器写作界面，生成了操作的标题，但是代码部分未显示
4. 关闭 tuture up 并重新开启
5. 刷新浏览器 代码区域出现

**期望的行为逻辑**
git 记录操作之后，标题和代码同步出现

**屏幕截图**
出错时的屏幕截图（有 GIF 的话就更棒啦！）
<img width="1312" alt="Snipaste_2020-05-21_17-53-14" src="https://user-images.githubusercontent.com/11958607/82547236-f916c580-9b8b-11ea-993e-ff426fb09d2e.png">

**Comment by pftom** [comment]
@AutumnFish 非常感谢，您提到的这些问题，我们已经修复啦，今晚会发布一个新版本，敬请期待✌️

**Comment by pftom** [comment]
@AutumnFish 问题已经在 0.0.6 里面修复啦
