### ISSUE TITLE
浏览器卡顿

### ISSUE THREAD

**Issue by AutumnFish** [tuture-dev/tuture#295]
**简要描述 Bug**
tuture之后打开的浏览器编辑界面出现卡顿情况

**Tuture 版本信息**
@tuture/cli/0.0.6 darwin-x64 node-v13.13.0

**详细的报错调用栈信息**
没有错误信息

**复现步骤**
复现 Bug 的完整步骤：

1. 项目中如果有 package-lock.json 或者 yarn.lock 文件
2. 在tuture up 之后浏览器直接卡主不动

**期望的行为逻辑**
顺滑的编辑

**屏幕截图**

**Comment by pftom** [comment]
@AutumnFish 感谢！我们近期马上修复一下！

**Comment by pftom** [comment]
@AutumnFish 最新的 PR 里面已经修复了这个问题，您可以在项目根目录添加 `.tutureignore` 来忽略相关的会导致卡顿的文件
